Nazar zvarych branch
Bandura2/Homework pull request #1
Opened 2022-12-13 22:39 UTC by Bandura2

2022-12-14 18:12 UTC, artur-zhdan requested changes
Overall the code is good. just do some minor changes

2022-12-14 18:12 UTC, artur-zhdan commented on Laba_5.h
> +float comparing(float array_prices[], vector<Sneaker> comparable_vector,int size)
Function name should start with uppercase

2022-12-14 18:12 UTC, artur-zhdan commented on Laba_5.h
> +    void Sort(float arr[], int size)
unclear function functionality - what is the rule for sorting? Please, provide a brief comment about it

2022-12-14 18:12 UTC, artur-zhdan commented on Laba_5.h
> +int comparing(int array_sales[], vector<Sneaker> comparable_vector,int size)
Function name should start with uppercase.
In addition you may prefer using templates for function declaration if you need it for different types.

2022-12-14 18:12 UTC, artur-zhdan commented on main.cpp
> +  for(int temporary_index = 0; temporary_index < num_object; temporary_index++)
add four spaces/tab

2022-12-14 18:12 UTC, artur-zhdan commented on main.cpp
> +    for(int temporary_index = 0; temporary_index < num_object; temporary_index++)
better use just "i" as index

2022-12-14 18:12 UTC, artur-zhdan commented on main.cpp
> +  for(int temporary_index = 0; temporary_index < num_object; temporary_index++)
use "i" as index

2022-12-14 18:12 UTC, artur-zhdan commented on main.cpp
> +    for(int temporary_index = 0; temporary_index < num_object; temporary_index++)
"i"

2022-12-14 18:12 UTC, artur-zhdan commented on main.cpp
> +    SportShoesStore object_for_sort;
if you use this object just for two methods, without fields, you should declare functions separately. no need for a redundant object

2022-12-14 18:12 UTC, artur-zhdan commented on main.cpp
> +        for(int temporary_index = 0; temporary_index < num_object; temporary_index++)
"i"

2022-12-14 18:12 UTC, artur-zhdan commented on main.cpp
> +    int choise = 0;
choice not choise

2022-12-21 17:09 UTC, artur-zhdan approved these changes

2023-02-24 21:43 UTC, zveres-ss requested changes

2023-02-24 21:43 UTC, zveres-ss commented on Laba_5.h
> +    void Sort_array(float arr[], int size)  /*Bubblesort*/
either SortArray or sort_array

2023-05-08 13:09 UTC, merged